function LifeAtDSU() {
	var description = "After a year working full-time as an electrical engineer at Microsemi, I started attending\
    classes at Dakota State University (DSU)."
	document.getElementById("course-title").innerHTML = "<h5 style=\"color:#cc5200\">Life at DSU</h5>";
	document.getElementById("course-description").innerHTML = description;
	document.getElementById("course-extra").innerHTML = "";
};

function INFS762() {
	var description = "The main concepts, components, and various architectures of Data Warehouse. Advanced data\
	analysis and optimization of Data Warehouse Design. Data Warehousing and OLAP tools. Applying data mining\
	algorithms to retrieve highly specialized information or knowledge about the data stored in the Data Warehouse."
	document.getElementById("course-title").innerHTML = "<h5 style=\"color:#cc5200\">Data Warehousing and Data Mining</h5>";
	document.getElementById("course-description").innerHTML = description;
	document.getElementById("course-extra").innerHTML = "";
};

function INFS772() {
	var description = "An introduction to programming for data analysis with an emphasis on	the analysis of large\
	datasets using python. In the first half of the course, students will learn the core of ideas of\
	programming - flow control, input and output, data structures (e.g., arrays, lists, trees and hash tables),\
	iteration and recursion, classes and object-oriented programming - through writing code to deal with Big Data\
	generated by social media sites such as Twitter.  In the second half of the course, students will learn how to\
	use Python for effective data analysis.  Specific topics addressed include: vector computation and mathematics\
	with NumPy, statistical computation with SciPy, working with tabular data with Pandas,\
	and implementing analytics algorithms using Python."
	document.getElementById("course-title").innerHTML = "<h5 style=\"color:#cc5200\">Programming for Data Analytics</h5>";
	document.getElementById("course-description").innerHTML = description;
	document.getElementById("course-extra").innerHTML = "";
};

function INFS774() {
	var description = "This course provides a broad understanding of the principles underlying Big Data analytics and\
	its applications in different domains using a hands-on approach with a state-of-the-art Big Data platform.\
	It provides a combination of essential business and technical skills related to Big Data analytics.  It provides a\
	combination of essential business and technical skills related to Big Data analytics.\
	<br> Business aspects of the course emphasized included\
	<li> Understanding the scope and role of Big Data in today’s organizations</li>\
	<li> Representative example scenarios and case studies of industry specific applications highlighting Big Data issues - volume, variety, velocity, and veracity</li>\
	<li> When to consider a Big Data Solution</li>\
	<li> The integration of Big Data initiatives as part of the overall business strategy to achieve “return to data” and competitive differentiation, and information governance issues.</li>\
	<br>Technical aspects of the course emphasized include\
	<li> Life cycle of a Big Data analytics solution with multiple entry points</li>\
	<li> Essential components of a Big Data	solution and technology platform</li>\
	<li> Key features of Hadoop and related technologies (e.g., MapReduce, HDFS, NoSQL)</li>\
	<li> Performing analytics with predictive models, text analytics, and streaming data</li>\
	<li> Data visualization and communication of analytical findings.</li>\
	State-of-the-art tools are integrated throughout the course to provide hands-on exercises with relevant techniques."
	document.getElementById("course-title").innerHTML = "<h5 style=\"color:#cc5200\">Big Data Analytics</h5>";
	document.getElementById("course-description").innerHTML = description;
	document.getElementById("course-extra").innerHTML = "";
};

function STAT700() {
	var description = "Fundamentals of statistical programming languages including descriptive and visual analytics\
	in R and SAS, and programming fundamentals of SAS and R including logic, loops, macros and functions."
	document.getElementById("course-title").innerHTML = "<h5 style=\"color:#cc5200\">Statistical Programming</h5>";
	document.getElementById("course-description").innerHTML = description;
	document.getElementById("course-extra").innerHTML = "";
};

function STAT701() {
	var description = "Builds upon knowledge of SLR, MLR, ANOVA, and basics of statistical inference. The class will\
	start by covering statistical graphics and the associated modern statistical computing language(s). The next\
	section of the class will focus on non- and semi-parametric	methods with a focus on the application and\
	interpretation of the methods. The last section of the class will focus on longitudinal and repeated measure\
	models and conclude with an overview of techniques from meta-analysis\
	and large-scale inference."
	document.getElementById("course-title").innerHTML = "<h5 style=\"color:#cc5200\">Modern Applied Statistics I</h5>";
	document.getElementById("course-description").innerHTML = description;
	document.getElementById("course-extra").innerHTML = "";
};

function STAT702() {
	var description = "Provides an introduction to data mining techniques from multivariate data such as Principal\
	Component Analysis, Multidimensional Scaling, and Cluster Analysis. From there we will move on to an introduction\
	to supervised learning methods and pattern recognition with a focus on algorithmic methods. The course will finish\
	with an overview of statistical prediction analysis relevant to business intelligence and analytics."
	document.getElementById("course-title").innerHTML = "<h5 style=\"color:#cc5200\">Modern Applied Statistics II</h5>";
	document.getElementById("course-description").innerHTML = description;
	document.getElementById("course-extra").innerHTML = "";
};

function INFS768() {
	var description = "Provides a broad understanding of the role of predictive analytics for decision-making in\
	different application domains. Students will be exposed to a number of predictive analytics techniques originated\
	in related fields of statistics, machine learning, and artificial intelligence. Techniques covered will include\
	statistical techniques such as linear and logistic regression, classification techniques such as decision trees\
	and neural networks, association analysis techniques such as market basket analysis, and cluster analysis techniques\
	such as K-means clustering. Applications of each of the techniques for decision-making applications will be\
	emphasized. Utilization of predictive analytics software is incorporated."
	document.getElementById("course-title").innerHTML = "<h5 style=\"color:#cc5200\">Predictive Analytics for Decision Making</h5>";
	document.getElementById("course-description").innerHTML = description;
	document.getElementById("course-extra").innerHTML = "";
};

function INFS770() {
	var description = "Provides an understanding of data mining methodology as well as hands-on experience with applying\
	the methodology in data mining applications.  Throughout the course, students will work closely with data analysis\
	following the data mining methodology. Different aspects of data mining such as data import, data partitioning,\
	variable transformation, model building, and model comparison will be covered. Students will participate in one\
	or more major data mining projects in the course. Through formal presentations students will gain experience in\
	delivering the findings to an audience in an effective manner. Utilization of predictive analysis software is incorporated."
	document.getElementById("course-title").innerHTML = "<h5 style=\"color:#cc5200\">Advanced Data Mining Applications</h5>";
	document.getElementById("course-description").innerHTML = description;
	document.getElementById("course-extra").innerHTML = "";
};

function ECON730() {
    var description = "This course utilizes micro- and macroeconomic theory and empirical analysis to improve decision-making \
    skills and incorporates significant information technology integration. Major microeconomics topics include demand analysis and estimation, \
    cost analysis and estimation, market structures, pricing strategies, and game theory. Major macroeconomics topics include \
    the operation of credit markets, monetary and fiscal policy, analysis and prediction of macroeconomic variables, foreign currency markets, \
    and international trade. Technology integration includes: The use of Internet-based resources to supply data for analysis and information \
    on current issues relevant to the course; the use of simulations, games, and computer applications to reinforce economic concepts; \
    and the introduction of software tools that enhance the summary and presentation of economic information in a professional setting."
    document.getElementById("course-title").innerHTML = "<h5 style=\"color:#cc5200\">Economics For Decision Making</h5>";
	document.getElementById("course-description").innerHTML = description;
	document.getElementById("course-extra").innerHTML = "";
}

function BADM712() {
    var description = "This course emphasizes the application of financial theory and concepts to the development of effective \
    financial strategies for maximization of the firm value and shareholder wealth. Topics include capital budgeting, cash flow analysis, \
    capital structure, cost of capital, working capital management, and security valuation, as well as effective spreadsheet analyses."
    document.getElementById("course-title").innerHTML = "<h5 style=\"color:#cc5200\">Advanced Business Finance</h5>";
	document.getElementById("course-description").innerHTML = description;
	document.getElementById("course-extra").innerHTML = "";
}