document.getElementById("header-text").innerHTML = "<a href=\"dsu\"><img src=\"img/Banners/DSU_Banner.png\"></a>";

function LifeAtDSU() {
	var description = "After a year working full-time as an electrical engineer at Microsemi, I started attending\
    classes at Dakota State University (DSU)."
	document.getElementById("course-title").innerHTML = "Life at DSU";
	document.getElementById("course-description").innerHTML = description;
};

function INFS762() {
	var description = "This course focuses on the concepts, techniques, and tools used to manage and analyze \
	large datasets. Topics include the design and architecture of data warehouses, data modeling, ETL \
	(Extract, Transform, Load) processes, and OLAP (Online Analytical Processing). The course also covers data \
	mining techniques such as clustering, classification, association analysis, and anomaly detection. Students \
	will learn how to apply these methods to uncover patterns, trends, and insights from large datasets, using \
	tools like SQL, Python, and specialized data mining software. The course emphasizes practical applications \
	in business, healthcare, and other industries."
	document.getElementById("course-title").innerHTML = "Data Warehousing and Data Mining";
	document.getElementById("course-description").innerHTML = description;
	document.getElementById("course-extra").innerHTML = "";
};

function INFS772() {
	var description = "An introduction to programming for data analysis with an emphasis on	the analysis of large\
	datasets using python. In the first half of the course, students will learn the core of ideas of\
	programming - flow control, input and output, data structures (e.g., arrays, lists, trees and hash tables),\
	iteration and recursion, classes and object-oriented programming - through writing code to deal with Big Data\
	generated by social media sites such as Twitter.  In the second half of the course, students will learn how to\
	use Python for effective data analysis.  Specific topics addressed include: vector computation and mathematics\
	with NumPy, statistical computation with SciPy, working with tabular data with Pandas,\
	and implementing analytics algorithms using Python."
	document.getElementById("course-title").innerHTML = "Programming for Data Analytics";
	document.getElementById("course-description").innerHTML = description;
};

function INFS774() {
	var description = "This course provides a comprehensive understanding of Big Data analytics principles and \
	their applications across various industries. It covers both business and technical aspects, including the \
	role of Big Data in organizations, industry-specific case studies, and how to integrate Big Data solutions \
	into business strategies. On the technical side, it focuses on the Big Data solution lifecycle, key technologies \
	like Hadoop, MapReduce, HDFS, and NoSQL, as well as analytics methods such as predictive models, text analysis, \
	and streaming data. Students will gain hands-on experience with state-of-the-art tools for data visualization \
	and communication of analytical results."
	document.getElementById("course-title").innerHTML = "Big Data Analytics";
	document.getElementById("course-description").innerHTML = description;
};

function STAT700() {
	var description = "This course focuses on the application of programming techniques to analyze and interpret \
	data using statistical methods. Topics include data manipulation, statistical modeling, hypothesis testing, \
	and visualization using programming languages such as R, Python, and SAS. The course emphasizes practical \
	skills for working with real-world datasets, performing exploratory data analysis, and implementing \
	statistical algorithms. Students will develop proficiency in writing efficient, reproducible code to solve \
	complex statistical problems and gain hands-on experience in using statistical programming to \
	support data-driven decision-making.<br><br>\
    <div id=\"STAT700_description\">\
      <a onclick=\"STAT700_Report()\" target=\"_blank\"><button type=\"submit\">Final Report</button></a>\
    </div>"
	document.getElementById("course-title").innerHTML = "Statistical Programming";
	document.getElementById("course-description").innerHTML = description;
};

function STAT700_Report() {
    var description = "<iframe src=\"Storage\\DSU\\STAT700_Report.pdf#toolbar=0&view=FitH\" style=\"width: 100%;border: none;\"></iframe>"
    document.getElementById("STAT700_description").innerHTML = description;
}

function STAT701() {
	var description = "Builds upon knowledge of SLR, MLR, ANOVA, and basics of statistical inference. The class will\
	start by covering statistical graphics and the associated modern statistical computing language(s). The next\
	section of the class will focus on non- and semi-parametric	methods with a focus on the application and\
	interpretation of the methods. The last section of the class will focus on longitudinal and repeated measure\
	models and conclude with an overview of techniques from meta-analysis\
	and large-scale inference."
	document.getElementById("course-title").innerHTML = "Modern Applied Statistics I";
	document.getElementById("course-description").innerHTML = description;
};

function STAT702() {
	var description = "Provides an introduction to data mining techniques from multivariate data such as Principal\
	Component Analysis, Multidimensional Scaling, and Cluster Analysis. From there we will move on to an introduction\
	to supervised learning methods and pattern recognition with a focus on algorithmic methods. The course will finish\
	with an overview of statistical prediction analysis relevant to business intelligence and analytics."
	document.getElementById("course-title").innerHTML = "Modern Applied Statistics II";
	document.getElementById("course-description").innerHTML = description;
};

function INFS768() {
	var description = "Provides a broad understanding of the role of predictive analytics for decision-making in\
	different application domains. Students will be exposed to a number of predictive analytics techniques originated\
	in related fields of statistics, machine learning, and artificial intelligence. Techniques covered will include\
	statistical techniques such as linear and logistic regression, classification techniques such as decision trees\
	and neural networks, association analysis techniques such as market basket analysis, and cluster analysis techniques\
	such as K-means clustering. Applications of each of the techniques for decision-making applications will be\
	emphasized. Utilization of predictive analytics software is incorporated."
	document.getElementById("course-title").innerHTML = "Predictive Analytics for Decision Making";
	document.getElementById("course-description").innerHTML = description;
};

function INFS770() {
	var description = "Provides an understanding of data mining methodology as well as hands-on experience with applying\
	the methodology in data mining applications.  Throughout the course, students will work closely with data analysis\
	following the data mining methodology. Different aspects of data mining such as data import, data partitioning,\
	variable transformation, model building, and model comparison will be covered. Students will participate in one\
	or more major data mining projects in the course. Through formal presentations students will gain experience in\
	delivering the findings to an audience in an effective manner. Utilization of predictive analysis software is incorporated."
	document.getElementById("course-title").innerHTML = "Advanced Data Mining Applications";
	document.getElementById("course-description").innerHTML = description;
};

function ECON730() {
    var description = "This course utilizes micro- and macroeconomic theory and empirical analysis to improve decision-making \
    skills and incorporates significant information technology integration. Major microeconomics topics include demand analysis and estimation, \
    cost analysis and estimation, market structures, pricing strategies, and game theory. Major macroeconomics topics include \
    the operation of credit markets, monetary and fiscal policy, analysis and prediction of macroeconomic variables, foreign currency markets, \
    and international trade. Technology integration includes: The use of Internet-based resources to supply data for analysis and information \
    on current issues relevant to the course; the use of simulations, games, and computer applications to reinforce economic concepts; \
    and the introduction of software tools that enhance the summary and presentation of economic information in a professional setting."
    document.getElementById("course-title").innerHTML = "Economics For Decision Making";
	document.getElementById("course-description").innerHTML = description;
}

function BADM712() {
    var description = "This course focuses on the application of financial theories and quantitative methods \
    to benefit business decision-making. Topics include capital budgeting, cash flow analysis, capital \
    structure, cost of capital, working capital management, and security valuation, as well as effective \
    spreadsheet analyses. The course emphasizes the use of data analytics tools and techniques, such as \
    statistical analysis, financial forecasting, and optimization, to analyze financial markets, investments, \
    and corporate financial strategies. Students will develop the skills to interpret financial data, assess \
    investment opportunities, and make informed financial decisions in a rapidly changing business environment."
    document.getElementById("course-title").innerHTML = "Advanced Business Finance";
	document.getElementById("course-description").innerHTML = description;
}